# Generated by Django 5.0.6 on 2024-06-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuemSomos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Quem Somos', max_length=200)),
                ('conteudo', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='quem_somos_image/')),
            ],
        ),
    ]
