# Generated by Django 5.0.6 on 2024-07-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAprepi', '0004_historia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(default='Diretoria', max_length=100)),
                ('imagem_diretoria', models.ImageField(blank=True, null=True, upload_to='diretoria/')),
                ('descricao_diretoria', models.TextField(blank=True, null=True)),
                ('imagem_conselho_fiscal', models.ImageField(blank=True, null=True, upload_to='conselho_fiscal/')),
                ('descricao_conselho_fiscal', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
