# Generated by Django 5.0.6 on 2024-07-02 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAprepi', '0005_diretoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtaReuniao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='atas_reunioes/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='documentos_gerais/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
