# Generated by Django 5.0.6 on 2024-07-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAprepi', '0006_atareuniao_documentogeral'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrosselNoticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('resumo', models.TextField()),
                ('imagem', models.ImageField(upload_to='carrossel_imagens/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
