# Generated by Django 5.0.6 on 2024-07-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteAprepi', '0007_carrosselnoticia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('conteudo', models.TextField()),
                ('imagem', models.ImageField(upload_to='noticias/')),
                ('data_publicacao', models.DateField(auto_now_add=True)),
                ('categoria', models.CharField(choices=[('PREVENCAO', 'Prevencao'), ('IMPRENSA', 'Saiu na imprensa'), ('ARTIGOS', 'Artigos'), ('EVENTOS', 'Eventos')], max_length=20)),
            ],
        ),
    ]
